### ISSUE TITLE
Cmake build error: No such file or directory

### ISSUE THREAD

**Issue by predat** [zpelgrims/polynomialoptics#330] opened 2023-03-12 10:39 UTC
I'm trying to build lentil on linux (Centos7) but encounter an error:
```
CMake Error at src/CMakeLists.txt:44 (file):
  file failed to open for reading (No such file or directory):

    .../lentil/pota/build/src/lentil_camera.mtd
Call Stack (most recent call first):
  src/CMakeLists.txt:55 (cat)

```

**Comment by zpelgrims** [comment] 2023-03-12 10:47
Ah yes, I've seen this before but ignored it.

You can work around it by manually creating this file `lentil/pota/build/src/lentil_camera.mtd` (just empty). Then the build script will run.

We should probably correct this error, the cause of it is inside [src/CMakeLists.txt](https://github.com/zpelgrims/pota/blob/77754d90573e216fb9c8a45c36fe3b948cf8bd18/src/CMakeLists.txt), in the bottom section. Probably we just need to add a `touch [filename]`?

**Comment by predat** [comment] 2023-03-12 11:28
The build progresses by creating an empty file but now the file "lentilTemplate.py" is missing during the install.
(It seems to me that the CMake part is missing in the instructions concerning the compilation in the README.md (https://github.com/zpelgrims/lentil/blob/dev/README.md#L28))

**Comment by zpelgrims** [comment] 2023-03-12 11:54
After some investigation there's something worse happening - it seems the python script isn't being run when we build the project.

In the usual case, what happens is:

- The mtd/template files get constructed with a python script (uigen.py). The MTD files is then concatenated with another mtd file to include all of the shader's metadata.

Right now it seems like this python script isn't run at all:

```
add_custom_command(OUTPUT ${MTD} COMMAND python3 -B ARGS ${CMAKE_SOURCE_DIR}/src/uigen.py ${UI} ${MTD} ${AE} ${KARGS} ${CMAKE_CURRENT_BINARY_DIR} ${HTML} DEPENDS ${UI})
add_custom_target(${SHADER}UI ALL DEPENDS ${MTD})
```

I'm far from a cmake expert so I don't understand currently why this isn't ran. I will investigate but would love a second pair of eyes on this if you're experienced with cmake. 

Running the python file directly (with relevant arguments) works, so I think the issue is on the cmake side.

**Comment by zpelgrims** [comment] 2023-03-12 12:20
I got the build running by changing the way the python script is ran. You should be able to update to latest dev branch and try again. It's not very cmaky to do it this way (execute_process), but it does work on my end.

**Comment by predat** [comment] 2023-03-12 17:57
i just have to change
```
-   build_dir = sys.argv[8] if len(sys.argv) > 6 else os.path.abspath("")
+   build_dir = sys.argv[8] if len(sys.argv) > 6 else os.path.join(os.path.abspath(""), "src")
```
in pota/src/uigen.py to generate C4DtoA folder contents in correct folder.

**Comment by zpelgrims** [comment] 2023-03-12 18:17
Cool, that's working on my end. Want to become the first contributor and do a pull request?

**Comment by predat** [comment] 2023-03-12 20:28
sure, i've create a PR (https://github.com/zpelgrims/pota/pull/22)

**Comment by zpelgrims** [comment] 2023-03-12 20:34
PR merged, we'll close this issue. Thanks for the bit of cleanup as well :+1:

**Closed as completed by zpelgrims** 2023-03-12 20:34 UTC
